### ISSUE TITLE
Can prettifier be restricted to one branch?

### ISSUE THREAD

**Issue by lukesneeringer** [kevgo/prettifier#53]
This would be really useful for on-boarding it. I have a repo with about 20 open pull requests and installing the bot makes it run on all of them, causing potential merge conflicts and such. It would be nice to be able to start with the bot running on a side branch, get that committed, merge master into the other branches, and _then_ run the bot everywhere.

**Comment by kevgo** [comment]
In the [configuration file](https://github.com/kevgo/prettifier#configuration) you can list branches under the `excludeBranches` key and Prettifier won't check them. It's a blacklist right now. I can also add a whitelist for branches if that's better for you. 

Having said that, Prettifier should _reduce_ merge conflicts since it standardizes all branches to a common way of formatting, removing all whitespace differences in all branches.
